### ISSUE TITLE
Apply srt subs to all movies

### ISSUE THREAD

**Issue by DeuX01** [cglatot/pasta#37] opened 2020-12-10 14:08 UTC
First of all this tool is almost what I'm looking for (and it works great!)
I have a huge movie library but one of the major issues is that most remux files come with PGS subs. Few clients cannot play PGS subs without transcoding, so my solution was to setup sub-zero to get srt subs for all my movies. However, PGS subs are predefined over external SRT, so if there was a way to apply <language> srt preference to a entire library movie, it would save a TON of work hours to get everything working properly.

Thanks in advance

**Comment by cglatot** [comment] 2022-04-15 11:27
Going to close this as a duplicate of #35 - I will come up with some way to apply certain patterns to entire libraries for both Movies and TV shows.

**Closed by cglatot** 2022-04-15 11:27 UTC
Labels: duplicate, enhancement
